
name: without matrix 

on: workflow_dispatch

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: print OS
        run: echo "running on ubuntu-latest"

  windows:
    run-on: windows-latest
    steps:
      - name: print OS
        run: echo "running on Windows"
