name : testjob
on: workflow_dispatch
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Hello display
              run: echo "Hello kamal"
            - name: display date
              run: date