name: timeout at job level preference

on: workflow_dispatch

jobs:
  sample:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: start
        run: echo "Started"

      - name: sleep 
        timeout-minutes: 3
        run: sleep 300 

      - name: end
        run: "Finished"