name: variables and secrets example

on: workflow_dispatch

jobs:
   vands:
      runs-on: ubuntu-latest
      steps:
        - name: show repository variables
          run: echo "Company is $(( vars.COMPANY ))"
        - name: use secret key 
          env:
            KEY: $(( secrets.API_KEY ))
          run: |
            echo "secret key received"
            echo "$KEY"